include:
    - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v1.0.13
      inputs:
          vm-hostname: infrastructure.vm.xbhl.intranet
          vm-ssh-username: $SSH_USER
          vm-ssh-private-key: $SSH_PRIVATE_KEY
          service-name: openwebui
          container-name: openwebui
          container-location: /opt/containers/openwebui
          cloudflare-dns-entry-name: openwebui.intranet.xbhl.online
          cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
          cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
          container-healthcheck-delay: 60
          delete-existing-container-files: true

setup:generate-build-artifacts:
    script:
        - cp src/.env $BUILD_ARTIFACTS_DIR
        - echo "OPEN_WEBUI_HOST=${DNS_RECORD_NAME}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "VM_HOSTNAME=${VM_HOST}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> $BUILD_ARTIFACTS_DIR/.env
        - echo "GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}" >> $BUILD_ARTIFACTS_DIR/.env
