services:
    openwebui:
        container_name: openwebui
        image: ghcr.io/open-webui/open-webui:v0.11.3
        env_file:
            - envs/webui.env
            - envs/auth.env
            - envs/ai.env
            - envs/storage.env
            - envs/db.env
        volumes:
            - data:/app/backend/data
        networks:
            - openwebui
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.openwebui-router.rule=Host(`ai.intranet.xbhl.online`)"
            - "traefik.http.routers.openwebui-router.entrypoints=websecure"
            - "traefik.http.routers.openwebui-router.tls=true"
            - "traefik.http.routers.openwebui-router.service=openwebui"
            - "traefik.http.services.openwebui.loadbalancer.server.url=http://openwebui:8080"
            - "traefik.docker.network=proxy"
            - 'wud.watch=true'
            - 'wud.display.name=Open WebUI'
            - 'wud.display.icon=si:openai'
            - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
            - "wud.link.template=https://github.com/open-webui/open-webui/releases/tag/v$${major}.$${minor}.$${patch}"
        depends_on:
            chromadb:
                condition: service_healthy
            postgresdb:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    chromadb:
        container_name: openwebui_chromadb
        image: chromadb/chroma:1.5.9
        environment:
            - IS_PERSISTENT=TRUE
        volumes:
            - chromadb:/data
        networks:
            - openwebui
        labels:
            - 'wud.watch=true'
            - 'wud.display.name=ChromaDB (Open WebUI)'
            - 'wud.display.icon=mdi:database-search'
            - 'wud.tag.include=^\d+\.\d+\.\d+$$'
            - "wud.link.template=https://github.com/chroma-core/chroma/releases/tag/$${major}.$${minor}.$${patch}"
        healthcheck:
            test:
                [
                    "CMD",
                    "/bin/bash",
                    "-c",
                    "cat < /dev/null > /dev/tcp/localhost/8000",
                ]
            start_period: 5s
            interval: 10s
            timeout: 10s
            retries: 3
        restart: unless-stopped

    postgresdb:
        container_name: openwebui_postgres
        image: postgres:17.11
        shm_size: 128mb
        env_file:
            - envs/postgres.env
        volumes:
            - postgresdb:/var/lib/postgresql/data
        networks:
            - openwebui
        labels:
            - 'wud.watch=true'
            - 'wud.display.name=PostgreSQL (Open WebUI)'
            - 'wud.display.icon=si:postgresql'
            - 'wud.tag.include=^17\.\d+$$'
            - "wud.link.template=https://www.postgresql.org/docs/release/$${major}.$${minor}/"
        healthcheck:
            test: psql -U openwebui -d openwebui -c 'SELECT 1' || exit 1
            start_period: 5s
            timeout: 30s
            interval: 5s
            retries: 3
        restart: unless-stopped

    redis:
        container_name: openwebui_redis
        image: redis:8.10.1
        volumes:
            - redis:/data
        networks:
            - openwebui
        labels:
            - 'wud.watch=true'
            - 'wud.display.name=Redis (Open WebUI)'
            - 'wud.display.icon=si:redis'
            - 'wud.tag.include=^\d+\.\d+\.\d+$$'
            - "wud.link.template=https://github.com/redis/redis/releases/tag/$${major}.$${minor}.$${patch}"
        healthcheck:
            test: "redis-cli ping"
            start_period: 5s
            interval: 5s
            timeout: 3s
            retries: 5
        restart: unless-stopped

volumes:
    data:
    postgresdb:
    chromadb:
    redis:

networks:
    openwebui:
        name: openwebui-internal-network
    proxy:
        external: true
